/* eslint-disable linebreak-style */
/* eslint-disable no-param-reassign */
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchAllData } from './rocketLuanchApi';

const initialState = {
  items: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const rocketSync = createAsyncThunk(
  'rocketLuanch/rocketLuanchApi',
  async () => {
    const response = await fetchAllData();
    // The value we return becomes the `fulfilled` action payload
    return response;
  },
);

export const rocketSlice = createSlice({
  name: 'rocket',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(rocketSync.pending, (state) => {
        // pending... state
      })
      .addCase(rocketSync.fulfilled, (state, action) => {
        state.items = action.payload;
      });
  },
});

export const { increment, decrement, incrementByAmount } = rocketSlice.actions;
export const selectLuncher = (state) => state.rocket;

// export const selectCount = (state) => state.counter.value;
export default rocketSlice.reducer;
